apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nominatim.databaseSecret" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  databaseUrl: {{ include "nominatim.databaseUrl" . | b64enc }}
